version: '3.8'
services:
  scheduler:
    image: rss-feed-monitor:latest
    container_name: news_scheduler
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data:rw
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=UTC
    entrypoint: python src/scheduler.py
    command: --output slack